# Generated by Django 4.1.9 on 2023-05-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etalon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asparing",
                    models.FloatField(
                        default=0, verbose_name="Аспарагиновая кислота(Эталон)"
                    ),
                ),
                (
                    "glutamin",
                    models.FloatField(
                        default=0, verbose_name="Глутаминовая кислота(Эталон)"
                    ),
                ),
                ("serin", models.FloatField(default=0, verbose_name="Серин(Эталон)")),
                (
                    "gistidin",
                    models.FloatField(default=0, verbose_name="Гистидин(Эталон)"),
                ),
                (
                    "glitsin",
                    models.FloatField(default=0, verbose_name="Глицин(Эталон)"),
                ),
                (
                    "treonin",
                    models.FloatField(default=0, verbose_name="Треонин(Эталон)"),
                ),
                (
                    "arginin",
                    models.FloatField(default=0, verbose_name="Аргинин(Эталон)"),
                ),
                ("alanin", models.FloatField(default=0, verbose_name="Аланин(Эталон)")),
                (
                    "tirosin",
                    models.FloatField(default=0, verbose_name="Тирозин(Эталон)"),
                ),
                (
                    "tsistein",
                    models.FloatField(default=0, verbose_name="Цистеин(Эталон)"),
                ),
                ("valin", models.FloatField(default=0, verbose_name="Валин(Эталон)")),
                (
                    "metionin",
                    models.FloatField(default=0, verbose_name="Метионин(Эталон)"),
                ),
                (
                    "triptofan",
                    models.FloatField(default=0, verbose_name="Триптофан(Эталон)"),
                ),
                (
                    "fenilalalin",
                    models.FloatField(default=0, verbose_name="Фенилаланин(Эталон)"),
                ),
                (
                    "izoleitsin",
                    models.FloatField(default=0, verbose_name="Изолейцин(Эталон)"),
                ),
                (
                    "leitsin",
                    models.FloatField(default=0, verbose_name="Лейцин(Эталон)"),
                ),
                ("lisin", models.FloatField(default=0, verbose_name="Лизин(Эталон)")),
                ("prolin", models.FloatField(default=0, verbose_name="Пролин(Эталон)")),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="main.products",
                    ),
                ),
            ],
            options={
                "verbose_name": " -- (Аминокислотный Состав) -- ",
            },
        ),
    ]
