# Generated by Django 4.1.9 on 2023-06-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_monosaturated_polyunsaturated_saturatedfats_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="types",
            name="Category",
        ),
        migrations.AddField(
            model_name="categories",
            name="Types",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT, to="main.types"
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="Region",
            field=models.CharField(
                choices=[
                    ("Чуйская область", "Чуйская область"),
                    ("Иссык-кульская область", "Иссык-кульская область"),
                    ("Ошская область", "Ошская область"),
                    ("Таласская область", "Таласская область"),
                    ("Нарынская область", "Нарынская область"),
                    ("Джалал-Абадская область", "Джалал-Абадская область"),
                    ("Баткенская область", "Баткенская область"),
                    ("Эталон", "Эталон"),
                ],
                default="Чуйская область",
                max_length=50,
                verbose_name="Регион",
            ),
        ),
    ]
