# Generated by Django 4.1.9 on 2023-06-05 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_types_category_categories_types_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="types",
            options={"verbose_name": "Тип записи"},
        ),
        migrations.RemoveField(
            model_name="products",
            name="types",
        ),
        migrations.AddField(
            model_name="products",
            name="Categiry",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.categories",
                verbose_name="Категория продукта",
            ),
            preserve_default=False,
        ),
    ]
