# Generated by Django 4.1.9 on 2023-06-05 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_types_options_remove_products_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="Categiry",
        ),
        migrations.AddField(
            model_name="products",
            name="Category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.categories",
                verbose_name="Категория продукта",
            ),
        ),
    ]
