# Generated by Django 4.1.9 on 2023-06-06 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_products_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="Category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.categories",
                verbose_name="Категория продукта",
            ),
        ),
    ]
