# Generated by Django 4.1.9 on 2023-06-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_products_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=85, verbose_name="Наименование рецептуры"
                    ),
                ),
                (
                    "cost_price_100gramm",
                    models.FloatField(default=0, verbose_name="Себестоимость"),
                ),
                (
                    "cost_price_1kg",
                    models.FloatField(default=0, verbose_name="Себестоимость"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="staffs",
            name="amino_id",
        ),
        migrations.RemoveField(
            model_name="staffs",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="staffs",
            name="fatacid_id",
        ),
        migrations.RemoveField(
            model_name="staffs",
            name="minerals_id",
        ),
        migrations.RemoveField(
            model_name="staffs",
            name="product_id",
        ),
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mass_fraction",
                    models.FloatField(
                        default=0, verbose_name="Массовая доля в рецепте"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="main.products"
                    ),
                ),
                (
                    "recip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="main.recips"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="staffs",
            name="recip",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.recips",
            ),
            preserve_default=False,
        ),
    ]
