# Generated by Django 4.1.9 on 2023-06-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_recips_remove_staffs_amino_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatAcidCompositionOfMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "types",
                    models.CharField(
                        choices=[
                            (
                                "Насыщенные жирные кислоты, %",
                                "Насыщенные жирные кислоты, %",
                            ),
                            (
                                "Мононенасыщенные жирные кислоты, %",
                                "Мононенасыщенные жирные кислоты, %",
                            ),
                            (
                                "Полиненасыщенные жирные кислоты, %",
                                "Полиненасыщенные жирные кислоты, %",
                            ),
                        ],
                        default="Насыщенные жирные кислоты, %",
                        max_length=50,
                        verbose_name="Тип жирных кислоты",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Содержание")),
            ],
            options={
                "verbose_name": " -- (Жирнокислотный Состав) -- ",
            },
        ),
        migrations.RemoveField(
            model_name="fatacids",
            name="monosatured",
        ),
        migrations.RemoveField(
            model_name="fatacids",
            name="polyunsaturated",
        ),
        migrations.RemoveField(
            model_name="fatacids",
            name="product",
        ),
        migrations.RemoveField(
            model_name="fatacids",
            name="satured",
        ),
        migrations.AddField(
            model_name="fatacids",
            name="name",
            field=models.CharField(
                default=1, max_length=40, verbose_name="Название Жирнокислоты"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Monosaturated",
        ),
        migrations.DeleteModel(
            name="Polyunsaturated",
        ),
        migrations.DeleteModel(
            name="SaturatedFats",
        ),
        migrations.AddField(
            model_name="fatacidcompositionofmeal",
            name="fat_acid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.fatacids",
                verbose_name="Вид жирнокислоты",
            ),
        ),
        migrations.AddField(
            model_name="fatacidcompositionofmeal",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="main.products"
            ),
        ),
    ]
