# Generated by Django 4.1.9 on 2023-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_fatacidcompositionofmeal_remove_fatacids_monosatured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemicals",
            name="carbohydrates",
            field=models.FloatField(
                default=0, verbose_name="Массовая доля углевода, %"
            ),
        ),
    ]
