# Generated by Django 4.1.9 on 2023-06-12 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_chemicals_carbohydrates"),
    ]

    operations = [
        migrations.CreateModel(
            name="FatAcidsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Тип жирнокислоты"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Английский", "Английский"),
                            ("Русский", "Русский"),
                            ("Кыргызский", "Кыргызский"),
                        ],
                        default="Русский",
                        max_length=50,
                        verbose_name="Язык",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Regions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=50, verbose_name="Регион")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Английский", "Английский"),
                            ("Русский", "Русский"),
                            ("Кыргызский", "Кыргызский"),
                        ],
                        default="Русский",
                        max_length=50,
                        verbose_name="Язык",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="categories",
            name="language",
            field=models.CharField(
                choices=[
                    ("Английский", "Английский"),
                    ("Русский", "Русский"),
                    ("Кыргызский", "Кыргызский"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AddField(
            model_name="fatacidcompositionofmeal",
            name="language",
            field=models.CharField(
                choices=[
                    ("Английский", "Английский"),
                    ("Русский", "Русский"),
                    ("Кыргызский", "Кыргызский"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="language",
            field=models.CharField(
                choices=[
                    ("Английский", "Английский"),
                    ("Русский", "Русский"),
                    ("Кыргызский", "Кыргызский"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AddField(
            model_name="recips",
            name="language",
            field=models.CharField(
                choices=[
                    ("Английский", "Английский"),
                    ("Русский", "Русский"),
                    ("Кыргызский", "Кыргызский"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AddField(
            model_name="types",
            name="language",
            field=models.CharField(
                choices=[
                    ("Английский", "Английский"),
                    ("Русский", "Русский"),
                    ("Кыргызский", "Кыргызский"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="Region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="regions_category",
                to="main.regions",
            ),
        ),
    ]
