# Generated by Django 4.1.9 on 2023-06-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_fatacidstype_regions_categories_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Русский", "Русский"),
                    ("Кыргызча", "Кыргызча"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="fatacidcompositionofmeal",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Русский", "Русский"),
                    ("Кыргызча", "Кыргызча"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="fatacidstype",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Русский", "Русский"),
                    ("Кыргызча", "Кыргызча"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Русский", "Русский"),
                    ("Кыргызча", "Кыргызча"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="recips",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Русский", "Русский"),
                    ("Кыргызча", "Кыргызча"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="regions",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Русский", "Русский"),
                    ("Кыргызча", "Кыргызча"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="types",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Русский", "Русский"),
                    ("Кыргызча", "Кыргызча"),
                ],
                default="Русский",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
    ]
