# Generated by Django 4.1.9 on 2023-06-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_categories_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatacidcompositionofmeal",
            name="types",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.fatacidstype",
                verbose_name="Тип жирных кислоты",
            ),
        ),
    ]
