# Generated by Django 4.1.9 on 2023-06-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_fatacidcompositionofmeal_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etalon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=85, verbose_name="Наименование продукта"
                    ),
                ),
                ("protein", models.FloatField(default=0, verbose_name="Белок")),
            ],
        ),
    ]
