# Generated by Django 4.1.9 on 2023-06-24 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_delete_etalon_remove_staffs_recip_recips_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recips",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
