# Generated by Django 4.1.9 on 2023-06-24 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_recips_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="recips",
            name="date_analis",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата проектирования"
            ),
        ),
    ]
