# Generated by Django 4.1.9 on 2023-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_aminoacidcompositionrecip_c_min_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "HOD"), (2, "Staff"), (3, "Science Staff")],
                default=1,
                max_length=10,
            ),
        ),
    ]
