# Generated by Django 4.2.2 on 2023-07-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aminoacidcomposition",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.products",
            ),
        ),
        migrations.AlterField(
            model_name="aminoacidcompositionrecip",
            name="recip",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.recips"
            ),
        ),
        migrations.AlterField(
            model_name="chemicals",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.products",
            ),
        ),
        migrations.AlterField(
            model_name="chemicalsrecip",
            name="recip",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.recips"
            ),
        ),
        migrations.AlterField(
            model_name="fatacidcompositionofmeal",
            name="fat_acid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.fatacids",
                verbose_name="Вид жирнокислоты",
            ),
        ),
        migrations.AlterField(
            model_name="fatacidcompositionofmeal",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.products"
            ),
        ),
        migrations.AlterField(
            model_name="fatacidcompositionofmeal",
            name="types",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.fatacidstype",
                verbose_name="Тип жирных кислоты",
            ),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.products"
            ),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="recip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.recips"
            ),
        ),
        migrations.AlterField(
            model_name="mineralcomposition",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.products",
            ),
        ),
    ]
