# Generated by Django 4.2.6 on 2024-02-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_fatacidcompositionofmeal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='Types',
        ),
        migrations.AddField(
            model_name='fatacids',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Русский', 'Русский'), ('Кыргызча', 'Кыргызча')], default='Русский', max_length=50, verbose_name='Язык'),
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
